### ISSUE TITLE
Create a Wasabi daemon process (RPC?), so others can build stuff on top.

### ISSUE THREAD

**Issue by nopara73** [zkSNACKs/Meta#12]

**Comment by MaxHillebrand** [comment]
Both [RPC](https://github.com/zkSNACKs/WalletWasabi/pull/1449) [although a work in progress and not merged] and [headless daemon](https://docs.wasabiwallet.io/using-wasabi/Daemon.html) are implemented.

**Comment by molnard** [comment]
https://github.com/zkSNACKs/WalletWasabi/pull/1449
