### ISSUE TITLE
Integrate Payment Protocol from Bitpay (BIP 70)

### ISSUE THREAD

**Issue by JuniperTonic** [zkSNACKs/Meta#28]
Just to start it looks like a variation of this topic is already being discussed, which already lays out some of my concerns. [Meta/Bustapay integration](https://github.com/zkSNACKs/Meta/issues/23)
### Is your feature request related to a problem? Please describe.

When trying to spend BTC from Wasabi wallet, there is no way to send BTC to BitPay backed merchants. I currently have to send to another wallet and process the payment from there.

### Describe the solution you'd like

Here are some links to the "Payment Protocol" that BitPay uses. They created a JSON interface to help wallet integration.
[FAQ of Payment Protocol](https://support.bitpay.com/hc/en-us/articles/360015839672-Frequently-Asked-Questions-About-BitPay-and-Payment-Protocol-BIP70-)
[DEV Overview](https://blog.bitpay.com/payment-protocol-ecdsa-signatures/)
[JSON Payment Protocol Spec](https://github.com/bitpay/jsonPaymentProtocol/blob/master/specification.md)
This should serve as a starting point for anyone who want to look into it

### Describe alternatives you've considered

Will the BitPay server be upset if the payment is received from a different IP than the one logged at the merchants website?

A work around would be exposing a private key and just sweeping/signing a transaction from the other wallet

To even test this you have to open a BitPay merchant account. Does anyone have one that can be used on the testnet?

Feel free to move this request or provide input if this is not something that would work with Wasabi

**Comment by nopara73** [comment]
@JuniperTonic I transferred this issue to the Meta repo. I don't want to close this until I take a look at it myself, too.

**Comment by MaxHillebrand** [comment]
I agree with @NicolasDorier here, BIP 70 has many flaws, some discussed [here](https://github.com/bitcoin/bitcoin/pull/11622). 
Concept NACK.

**Comment by MaxHillebrand** [comment]
Yes @jameshilliard, and notice that Wasabi has already implemented BIP21 in https://github.com/zkSNACKs/WalletWasabi/pull/1949.

[@nopara73 I think you can close this issue]

**Comment by nopara73** [comment]
This is a discussion about BIP 70, not BIP 21.

**Comment by MaxHillebrand** [comment]
Can we close the issue?

**Comment by nopara73** [comment]
No. I did not do my own research yet.

**Comment by NicolasDorier** [comment]
I think Bitpay backtracked on BIP70. Sadly I could not check by myself, old services I was using before have all switched to btcpayserver.

**Comment by nopara73** [comment]
Obsolated. As @NicolasDorier said, BitPay does not do BIP70 anymore. Replacement issue: https://github.com/zkSNACKs/WalletWasabi/issues/3864
