### ISSUE TITLE
Hardware Wallet: Ledger Nano S Support

### ISSUE THREAD

**Issue by benthecarman** [zkSNACKs/Meta#31]
It would love to use this wallet but I prefer to store everything using cold storage with my Ledger Nano S.  If you guys could add support so this wallet is useable with a Ledger Nano S I would begin using this as my primary wallet instead of electrum.

**Comment by nopara73** [comment]
There are some difficulties in supporting hardware wallets, discussed here: https://github.com/zkSNACKs/Meta/issues/30

Since this is a larger breath conversation I moved this issue to the Meta repo.

**Comment by patrickmichalina** [comment]
This would be great. Similar to how Electrum works.
