### ISSUE TITLE
Lost Password Strategy

### ISSUE THREAD

**Issue by nopara73** [zkSNACKs/Meta#44]
It is common that users lose or mistype their passwords. While we have limited capabilities to prevent it, we still can do a few things. This issue aims to gather all the improvements we had in mind to help our users avoid losing their password.  

# Chinese Password Box

Mistyping passwords happen, because of carelessness. Our Chinese password box aims to break the usual flow of our users, hoping they will pay more attention not to make typos when choosing a password. It is also a cool feature.  

A possible improvement can be to add an info icon that would explain this experiment. However it would risk the degrading the effectiveness of this method, thus the user would calm down quickly and mistype his password anyway.

# Moving Password Confirmation To Next Page

This also aims to disrupt the flow of the user. If the user does not just have to repeat the password, but rather write password, do some other task, and confirm password, then it's more likely issues are caught before they happen.  

https://github.com/zkSNACKs/WalletWasabi/pull/1142

# Mnemonic and Password Tester

Mnemonic and Password tests can provide uncertain user certainty: https://github.com/zkSNACKs/WalletWasabi/issues/1143

# Password Typo Fixer  

The most common issue that the user mistypes his password. We have built a yet rudimentary password typo fixer that can look for possible mistypings: https://github.com/lontivero/WasabiPasswordFinder

Even though this is just a basic tool yet, this has already been proved to be useful: https://old.reddit.com/r/WasabiWallet/comments/amw7u6/invalid_password_to_coinjoin_anything_i_can_do/efpomuv/

This should make it into the wallet: 
https://github.com/zkSNACKs/WalletWasabi/issues/1035  

# Improving Security?

Since we are working at this part of the code, we can consider some security improvements to be added here.  

1. Once thing we could do is to provide additional entropy at wallet creation, for example with mouse movement?  
2. Another security improvement can be to add 2FA in a less intrusive way: https://github.com/zkSNACKs/Meta/issues/43

**Comment by nopara73** [comment]
This is mostly done.

**Comment by MaxHillebrand** [comment]
I've summarized this, and will further expand on it, in the new docs.
https://github.com/zkSNACKs/WasabiDoc/commit/4f6c3ed5611b40e3b2350f9456010e341eaaeb76
