### ISSUE TITLE
Wasabi on Tails

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/Meta#69]
### Wasabi + Tails = :heart: :fire: :rocket:

[Tails](https://tails.boum.org/) is a live operating system booted from a USB stick, due to it's amnesia nature it is often used for privacy sensitive tasks. There are some pre-installed applications on the OS by default, and they can be used after the first boot without downloading additional software.

Right now, there is electrum Wallet installed, and that's great, especially for off-line usage of cold storage. But because electrum's default network level privacy is near 0 - it thus is a misplaced tool for those who seek privacy with this OS. 

Wasabi solves the network level privacy of light client Bitcoin wallets, and with the inbuilt CoinJoin service and coin selection helps with timechain privacy as well. Thus I propose a marriage of these two awesome libre & open source projects.

I have questions about the following, and would like to start a conversation about this topic in general.

1. Are there any general issues with running Wasabi on Tails?
2. What is the extra storage and other hardware requirement for the USB stick, for all block filters and blocks of Wasabi?
3. What should be done when there is no network connection? Wasabi [unlike electrum] is useless then, because there's not [yet] a good off-line mode.
4. What are the step by step guides of installing Wasabi properly in persistent storage right now? This is something for the [docs](https://github.com/zksnacks/wasabidoc).
5. What are the requirements and procedure to get new software introduced to Tails by default?

Let's build this!!

**Comment by benthecarman** [comment]
Potential problems:

- Losing the wallet file would lose all labels

- CoinJoins require a hot wallet, if the user sends funds to this wallet and then the OS loses the wallet, the user will have lost their funds

**Comment by MaxHillebrand** [comment]
Yes, if Wasabi is installed in the amnesia part, then you are right.
But there is a persistent storage, and there can be software installed here. When the wallet files are persistent, then they are not lost upon shutdown.

**Comment by davterra** [comment]
I havent used Tails in years. Last time I did, setting it up with persistence was a bit tricky. It also defeats the main feature of Tails: being Read-Only. Unless they've made it easier to make a persistent instance of Tails, seems like it would be easier (and more secure) to install Wasabi on Whonix.

**Comment by nopara73** [comment]
Last time Electrum experienced the "update" attacks I researched this topic and it turned out to be a no-go. They wanted to remove Electrum altogether, but they got surprised by the fact that many of their users are using Electrum, so this software is pretty much baked into that OS now and they cannot remove it/replace it with Wasabi. The only way could be if Wasabi would support Electrum wallet files, but that's months of work, because Electrum has a lot of configuration that Wasabi doesn't.

**Comment by RiccardoMasutti** [comment]
Update: there's a Wasabi + Tails tutorial on docs now: https://docs.wasabiwallet.io/using-wasabi/WasabiSetupTails.html

**Comment by MaxHillebrand** [comment]
Yes, since we now have detailed documentation of how to use wasabi in tails, I am closing this issue now.
